name: webhook

on:
  issues:
    types: [opened, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

permissions: read-all

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Issue opened
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        TITLE: ':git_issue_opened: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) が作成されました'
        REPOSITORY: ${{ github.repository }}
        AUTHOR: ${{ github.event.sender.login }}
      uses: SSlime-s/traq-webhook@v2.0
      with:
        webhook-id: ${{ secrets.WEBHOOK_ID }}
        webhook-secret: ${{ secrets.WEBHOOK_SECRET }}
