name: webhook

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created]
  pull_request:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

permissions: read-all

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Issue opened
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        TITLE: ':git_issue_opened: [${{ github.event.issue.title }}](${{ github.event.issue.html_url }}) が作成されました'
        REPOSITORY: ${{ github.repository }}
        AUTHOR: ${{ github.event.sender.login }}
      uses: fjogeleit/http-request-action@master
      with:
        url: https://q.trap.jp/api/v3/webhooks/${{ secrets.WEBHOOK_ID }}
        method: 'POST'
        customHeaders: "{'X-TRAQ-Signature': ${{ secrets.WEBHOOK_SECRET }}"
        contentType: text/plain
        data: '\#\# ${{ env.TITLE }}\nリポジトリ: ${{ env.REPOSITORY }}\nissue作成者: ${{ env.AUTHOR }}'
