## webhook で traQ に送る用の actions
name: webhook

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, closed, review_requested]
  pull_request_review:
    types: [submitted]

permissions: read-all

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Message
        uses: SSlime-s/traq-webhook@v4.2
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          webhook-secret: ${{ secrets.WEBHOOK_SECRET }}
